version: '3.7'
services:
  strapi:
    container_name: prod
    build: ./docker/mongo/prod
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - mongo:mongo
    volumes:
      - ./app/mongo:/app
    ports:
      - '1337:1337'

  strapi-db:
    container_name: database
    build: ./docker/mongo/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    ports:
      - '27017:27017'
