version: '3.7'
services:
  prod:
    container_name: prod
    build:
      context: .
      dockerfile: ./docker/sqlite/prod/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '8080:8080'