version: '3.7'
services:
  rapid-api:
    container_name: api-dev
    build: ./docker/mongo/clean
    environment:
      PORT: 8080
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: rapid-api-db
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - rapid-api-db
    ports:
      - '8080:8080'

  rapid-api-db:
    container_name: api-db
    build: ./docker/mongo/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    ports:
      - '27017:27017'
