
###
GET http://localhost:8080/foos


###
GET http://localhost:8080/bars


###
GET http://localhost:8080/foos/1


###
POST http://localhost:8080/foos
content-type: application/json

{
  "id" : "1cb30a1385a5cf018f502eb1",
  "name": "Try More Foo",
  "description": "Muhaha"
}


###
POST http://localhost:8080/bars
content-type: application/json

{
  "id" : "3aadcd1385a5cf018f505f7c",
  "name": "How about this bar?",
  "description": "Posted with Id"
}


###
PUT http://localhost:8080/bars/3aadcd1385a5cf018f505f7c

{
  "name": "Updated It",
  "description": "Should have new text"
}


