
###
GET http://localhost:8080/examples


###
GET http://localhost:8080/no-endpoint


###
POST http://localhost:8080/examples

{
  "Name": "API Fail",
  "Description": "Will create empty record due to missing content type header"
}


###
POST http://localhost:8080/examples
content-type: application/json

{
  "Name": "API Example",
  "Description": "Added using API"
}


###
PUT http://localhost:8080/examples/2
content-type: application/json

{
  "Name": "Updated Example",
  "Description": "Used HTTP PUT to overwrite file"
}