
###
GET http://localhost:8080/examples


###
GET http://localhost:8080/no-endpoint


###
POST http://localhost:8080/examples

{
  "Name": "API Fail",
  "Description": "Will create empty record due to missing content type header"
}


###
POST http://localhost:8080/examples
content-type: application/json

{
  "name": "API Example",
  "description": "Added using API"
}


###
PUT http://localhost:8080/examples/1

{
  "name": "Updated Example",
  "description": "Used HTTP PUT to overwrite file"
}