FROM mongo:4.2.6-bionic

LABEL maintainer "Arnoud Kleinloog"
LABEL description "MongoDB instance initialized with default Clinical Algorithms"

#ENV MONGO_INITDB_ROOT_USERNAME mongoAdminUsr
#ENV MONGO_INITDB_ROOT_PASSWORD MonGoPw42_Ad
#ENV MONGO_INITDB_DATABASE admin

# COPY seed-data.js /docker-entrypoint-initdb.d/

